POST http://localhost:3000/pets/add HTTP/1.1
Content-Type : application/json

  {
    "name": "Bella",
    "species": "Dog",
    "age": 4,
    "state": "rescued"
  }
  
# [
#   {
#     "name": "Bella",
#     "species": "Dog",
#     "age": 4,
#     "state": "rescued"
#   },
#   {
#     "name": "Oscar",
#     "species": "Cat",
#     "age": 1,
#     "state": "rescued"
#   }
# ]
